repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.1
    hooks:
      - id: ruff
        types_or: [python, pyi]
      - id: ruff-format
        types_or: [python, pyi]
  - repo: https://github.com/allganize/ty-pre-commit
    rev: v0.0.18
    hooks:
      - id: ty-check
        additional_dependencies:
          - requests
          - paramiko
          - click
          - tqdm
          - aiohttp
          - pytest==9.0.2
          - pytest-asyncio
          - couchbase
          - opentelemetry-api
          - opentelemetry-sdk
          - opentelemetry-exporter-otlp-proto-grpc
          - packaging
          - deepdiff
          - pyjson5
          - Deprecated
          - netifaces
          - types-netifaces
          - psutil
          - pyyaml
          - websocket-client
        types_or: [python, pyi]
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.21.0
    hooks:
      - id: pyupgrade
        args: [--py310-plus]
        types_or: [python, pyi]
